

```{r}
library(tidyverse)
library(palmerpenguins)
library(paletteer)
```

## Base plots

```{r}
# Base plot with categorical color scale
cat_color_plot <- ggplot(penguins, aes(x = bill_length_mm, y = bill_depth_mm, color = species, shape = species)) +
  geom_point(size = 4, alpha = 0.8)

cat_color_plot 
```

```{r}
# Base plot with continuous color scale
cont_color_plot <- ggplot(penguins, aes(x = bill_length_mm, y = bill_depth_mm, color = body_mass_g)) +
  geom_point(size = 4, alpha = 0.8) 

cont_color_plot 
```

## Viridus color scales

```{r}
cont_color_plot +
  scale_color_viridis_c(option = "magma")
```

# RColorBrewer color scales

```{r}
RColorBrewer::display.brewer.all(colorblindFriendly = TRUE)
```

## Can use paletteer to apply palettes from many packages

```{r}
cat_color_plot +
  paletteer::scale_color_paletteer_d("calecopal::superbloom3")
```



# Import national parks color palletes

```{r}
my_parks_palette <- NatParksPalettes::natparks.pals(name = "WindCave", n = 20, type = "continuous")

cont_color_plot +
  scale_color_gradientn(colors = rev(my_parks_palette))
```

## Custom palettes

```{r}
# Build custom palette
my_palette <- c("#32DE8A", "#E36414", "#0F4C5C")
```

```{r}
cat_color_plot +
  scale_color_manual(values = my_palette)
```

```{r}
my_palette <- c("7AEEE9", "274948")

ggplot(penguins, aes(x = bill_length_mm, y = bill_depth_mm, color = body_mass_g)) +
  geom_point(size = 4, alpha = 0.8) +
  scale_color_gradientn(colors = my_palette)
```


## Apply colors to specific observations

```{r}
penguins |> 
  mutate(
    my_color = case_when(
      body_mass_g > 6000 ~ "#D7263D",
      TRUE ~ "gray50"
    )
  ) |> 
  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = my_color)) +
  geom_point(size = 4, alpha = 0.8) +
  scale_color_identity(guide = "legend", 
                       name = "Body mass (g)", labels = c(">6000", "<= 6000"))
```



